apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: firstblog 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: firstblog 
    spec:
      containers:
        - name: firstblog 
          image: g7tcoreacr.azurecr.io/firstblog
          ports:
          - containerPort: 8080